### ISSUE TITLE
names within the R chunk

### ISSUE THREAD

**Issue by leynu** [aaronbaggett/youngmetro#1]
\scriptsize 
```{r, echo = TRUE}
some_vector <- c("Erik", "Statistiker")
names(some_vector) <- c("Name", "Profession")

some_vector
```

this small chunk comes out wrong in the pdf output. It writes 
n      (some_vector) <- c("Name", "Profession")
instead of 
names(some_vector) <- c("Name", "Profession")

 .Not sure if it related to your beamer template or not. 

![skarmavbild 2018-03-08 kl 17 38 45](https://user-images.githubusercontent.com/31473019/37163279-9ef48970-22f7-11e8-9bd0-e572ab43438a.png)

**Comment by aaronbaggett** [comment]
That's strange. I was not able to reproduce the issue.
[r_code_test.zip](https://github.com/aaronbaggett/youngmetro/files/1793974/r_code_test.zip)

**Comment by leynu** [comment]
Hej!

Yes your example works just fine!
I have been adding chuncks to you example just to see when it was losing control.
But sometimes it was looking fine and sometimes not under I realized something.

It was at the Rstudio: View PDF where I was observing the error NOT in the pdf file.
I am not good at programming so I don’t know why this happens

This are my setting if it can be to any use:
platform       x86_64-apple-darwin15.6.0
arch           x86_64
os             darwin15.6.0
system         x86_64, darwin15.6.0
status
major          3
minor          4.3
year           2017
month          11
day            30
svn rev        73796
language       R
version.string R version 3.4.3 (2017-11-30)
nickname       Kite-Eating Tree


Best regards, Leyla






Från: Aaron Baggett <notifications@github.com>
Svara till: aaronbaggett/youngmetro <reply@reply.github.com>
Datum: torsdag 8 mars 2018 17:48
Till: aaronbaggett/youngmetro <youngmetro@noreply.github.com>
Kopia: Leyla Nunez <leyla.nunez@rccvast.se>, Author <author@noreply.github.com>
Ämne: Re: [aaronbaggett/youngmetro] names within the R chunk (#1)


That's strange. I was not able to reproduce the issue.
r_code_test.zip<https://github.com/aaronbaggett/youngmetro/files/1793974/r_code_test.zip>
