### ISSUE TITLE
title graphic too close to the right edge

### ISSUE THREAD

**Issue by michalovadek** [aaronbaggett/youngmetro#2]
Hi, thanks for creating the template. I replaced the stock title graphic with my own but I find it to be placed too close to the right-hand edge of the slide. I think it would look neater if there was a similar amount of white space as on the left edge. There is also the danger that on some projectors/screens the edges of the slides might not be visible. Is there an easy way to fix this and/or manipulate the distance of the graphic from the edge?

**Comment by aaronbaggett** [comment]
Unfortunately, I have encountered the same issue. I often have to just go into the source file and reposition, compile, reposition, compile, etc. See lines 517-518 of template.tex.
